### ISSUE TITLE
Can't generate tabs

### ISSUE THREAD

**Issue by juperdat** [sumpfork/dominiontabs#142] opened 2017-01-09 02:12 UTC
Every time I click Generate button nothing appears. Under the Global Styles tab it tells me I need to check every box. I'm using Google Chrome. I used it in December and it looks as if the format has changed.

**Comment by juperdat** [comment] 2017-01-09 02:20
Nevermind. Working now.

**Comment by sumpfork** [comment] 2017-01-09 02:20
Dupe of #141.

**Closed by sumpfork** 2017-01-09 02:20 UTC
