### ISSUE TITLE
Option to sort base cards separately

### ISSUE THREAD

**Issue by JesseMFrey** [sumpfork/dominiontabs#144] opened 2017-01-21 19:57 UTC
I would like to have base cards separate from other cards. I know that I can print dividers for base cards but then when I take them out of the other cards the alternating tabs won't be correct.

**Comment by wvoigt** [comment] 2017-01-22 14:44
@JesseMFrey can you be more specific on the options you are using that **don't** separate the base cards?

**Comment by fifguy85** [comment] 2017-01-25 00:56
I believe the example being referred to above is printing left-right alternate tabs for Dominion 1st Edition (which includes the base cards) and wanting to exclude the base cards so that the tabs alternate left and right correctly for the ordering of cards chosen.

**Comment by wvoigt** [comment] 2017-01-25 02:14
Maybe counter intuitive,  but if you add the base cards, I believe it does what you want.  Assuming you order by expansion. It gives base cards, then Dominion cards without base cards.

**Comment by JesseMFrey** [comment] 2017-01-25 02:21
so it does.
Thanks

**Comment by fifguy85** [comment] 2017-01-30 19:26
I can confirm this as well. This request can probably be closed as possible through an existing workaround.

**Comment by nickv2002** [comment] 2017-01-30 19:48
Closed since you can accomplish this through current system: No need for additional options.

**Closed** 2017-01-30 19:47 UTC
