### ISSUE TITLE
Asterisks in "Plunder Extras"

### ISSUE THREAD

**Issue by bszonye** [sumpfork/dominiontabs#435] opened 2023-01-03 09:52 UTC
Looking at the expansion dividers, I noticed that the divider for `*Plunder Extras*` has asterisks in the name, unlike all of the other similar sections like `Adventures Extras`. I don't see anything obvious in the code or card db that would cause this.

![image](https://user-images.githubusercontent.com/5016349/210334211-5cd829e5-742f-4298-bd9b-1418751e6dea.png)

**Comment by md5i** [comment] 2023-01-03 14:47
I was assuming that this was an error caused by my script that converted data from wikitext, but I can't find anything in the repo that I would have thought would have caused that.

**Comment by md5i** [comment] 2023-01-03 14:50
Ah.  This could be caused by a _lack_ of a `plunder extras` entry (or a `plunder` entry) in `sets_en_us.json`.  I don't think I touched this file, but it looks like I was supposed to.  Is that right?

**Comment by md5i** [comment] 2023-01-03 16:23
Yup, that did it.  Pull request added.

**Comment by sumpfork** [comment] 2023-01-07 19:36
Fixed with #437

**Closed by sumpfork** 2023-01-07 19:36 UTC
